
project_id = "ulebotjrsgheybhpdnxd"

[functions.create-stripe-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false
